name: API Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove old container
        run: |
          CONTAINER_NAME="your_container_name"
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          
      - name: Build and run new container
        run: |
          docker build -t $IMAGE_NAME .
          docker run -d --name $CONTAINER_NAME -p 80:80 $IMAGE_NAME
        working-directory: .



