name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      CONTAINER_NAME: your_container_name
      IMAGE_NAME: your_image_name
      PORT_NUMBER: 80
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display container name
        run: |
          echo "Container Name: $CONTAINER_NAME"

      - name: Stop and remove old container
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: Build and run new container
        run: |
          docker build -t $IMAGE_NAME .
          docker run -d --name $CONTAINER_NAME -p $PORT_NUMBER:80 $IMAGE_NAME
