name: API Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      IMAGE_NAME: bikeshare-api:v1.0
      CONTAINER_NAME: bikeshare-container
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove old container
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: Build and run new container
        run: |
          docker build -t $IMAGE_NAME -f path/to/Dockerfile .
          docker run -d --name $CONTAINER_NAME -p 8001:80 $IMAGE_NAME
        working-directory: ./bikeshare_project
